# Generated by Django 3.2.5 on 2022-01-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Member', '0003_auto_20220127_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile pictures'),
        ),
        migrations.AlterField(
            model_name='student',
            name='blood',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='upazila',
            field=models.CharField(choices=[('Jhalokathi Sadar', 'Jhalokathi Sadar'), ('Nalcity', 'Nalcity'), ('Rajapur', 'Rajapur'), ('Kathalia', 'Kathalia')], max_length=100),
        ),
    ]
