# Generated by Django 3.2.5 on 2022-01-31 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Member', '0004_auto_20220127_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='gender',
        ),
        migrations.AddField(
            model_name='teacher',
            name='designation',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
