# Generated by Django 3.2.12 on 2022-02-08 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Member', '0009_alter_notice_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='tittle',
        ),
        migrations.AddField(
            model_name='notice',
            name='title',
            field=models.TextField(default=4, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notice',
            name='body',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.CreateModel(
            name='NoticeImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='notice')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_Member.notice')),
            ],
        ),
    ]
